apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: github-rbac-policy
  namespace: mcp
spec:
  targetRefs:
    - name: github-mcp-backend
      kind: Backend
      group: gateway.networking.k8s.io
  rbac:
    policy:
      matchExpressions:
          - 'mcp.tool.name in ["search_code", "get_file_contents", "get_pull_request", "create_or_update_file", "create_branch", "list_pull_requests", "create_pull_request"]'
