apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: github-mcp-server
  namespace: mcp
spec:
  deployment:
    args:
    - 'stdio'
    cmd: "/server/github-mcp-server"
    image: ghcr.io/github/github-mcp-server
    port: 3000
    secretRefs:
    - name: github-mcp-secret
  transportType: stdio
---
apiVersion: v1
data:
  GITHUB_PERSONAL_ACCESS_TOKEN: $GITHUB_PERSONAL_ACCESS_TOKEN
kind: Secret
metadata:
  name: github-mcp-secret
  namespace: mcp
type: Opaque