apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: github-mcp-server
  namespace: kagent
spec:
  description: ""
  protocol: STREAMABLE_HTTP
  sseReadTimeout: 5m0s
  terminateOnClose: true
  timeout: 30s
  url: http://github-mcp-server.mcp.svc.cluster.local:3000/mcp
