apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gpt-4.1-pro-model-config 
  namespace: kagent
spec:
  apiKeySecret: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
  model: gpt-4.1-pro
  provider: OpenAI